env_file: env
mirrors_timer_name: local_mirrors_list
dbs_timer_name: dbs_update
update_mirrors_list_script_path: "/usr/bin/{{ mirrors_timer_name }}.sh"
update_maxmind_dbs_script_path: "/usr/bin/{{ dbs_timer_name }}.sh"
service_user: "mirror-service"
source_path: "/home/{{ service_user }}/mirrors_service"
sentry_environments:
  - "Production"
  - "Staging"
ansible_dnf_packages:
  - python3
  - python3-libselinux
  - python3-libsemanage
dnf_packages:
  - python39
  - python39-devel
  - git
  - redis
  - nginx
  - gcc
  # for testing purposes
  - sqlite
python_packages:
  - aiodns==3.0.0
  - aioredis[hiredis]==2.0.0
  - alembic==1.7.1
  - beautifulsoup4==4.10.0
  - blinker==1.4
  - dataclasses==0.6
  - dateparser==1.0.0
  - geopy==2.2.0
  - Flask-BS4==5.0.0.1
  - flask==2.0.1
  - flask[async]==2.0.1
  - flask_api==3.0.post1
  - geoip2==4.2.0
  - haversine==2.5.1
  - jsonschema==3.2.0
  - Jinja2==3.0.1
  - lxml==4.6.3
  - pyyaml==5.4.1
  - redis==3.5.3
  - requests==2.26.0
  - sentry-sdk[flask]==1.4.3
  - sqlalchemy==1.4.23
  - uwsgi==2.0.19.1
  - Werkzeug==2.0.1
