ansible_dnf_packages:
  - python3
  - python3-libselinux
  - python3-libsemanage
dnf_packages:
  - python3.12
  - python3.12-devel
  - git
  - nginx
  - gcc
  - epel-release
  - nfs-utils
  # for testing purposes
  - checkpolicy
  - sqlite
  - bash-completion
  - setools-console
python_packages:
  - aiodns==4.0.0
  - aiohttp-retry==2.9.1
  - alembic==1.16.4
  - beautifulsoup4==4.13.5
  - dateparser==1.2.2
  - Flask-BS4==5.3.1.0
  - flask[async]==3.1.2
  - git+https://github.com/flask-api/flask-api/
  - flask-caching==2.3.1
  - geopy==2.4.1
  - gunicorn[gthread]==23.0.0
  - haversine==2.9.0
  - jsonschema==4.25.1
  - lxml==6.0.1
  - maxminddb==2.8.2
  - pycountry==24.6.1
  - pyyaml==6.0.2
  - redis==6.4.0
  - requests==2.32.5
  - sentry-sdk[flask]==2.35.0
  - sqlalchemy==2.0.43
  - geoip2==5.1.0
